# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  demands:
  - npm
  - maven


steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Maven@1
  displayName: Maven

- task: whitesource.whiteSource-bolt-v2.bolt.wss.WhiteSource@21
  displayName: WhiteSource
  inputs:
    projectName: WebGoat

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'